apiVersion: v1
kind: Service
metadata:
  name: fiap-burger-api-svc
spec:
#  type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
      nodePort: 31000
  selector:
    app: fiap-burger-api