apiVersion: apps/v1
kind: Deployment
metadata:
  name: tech-challenge-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tech-challenge-java
  template:
    metadata:
      labels:
        app: tech-challenge-java
    spec:
      containers:
      - name: tech-challenge-java
        image: "target/fiapBurger-0.0.1-SNAPSHOT.jar" 
        ports:
        - containerPort: 8989
