name: '1 - [feat] Build & Pull Request'

on:
  push:
    branches:
      - 'feature/**'
permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2


      # No final da esteira, abra um pull request para a branch main
      - name: Abrir pull request para main
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: "Merge da feature para main"
          body: |
            Este pull request foi automaticamente gerado pelo GitHub Actions.
            Por favor, revise as mudanças e faça o merge se estiverem corretas.