name: Feature Branch Workflow

on:
  push:
    branches:
      - 'feature/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests (replace with your validation steps)
        run: |
          # Coloque aqui os comandos para validar a feature

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Automatically created Pull Request"
          branch: main
          title: "Automatically created Pull Request"
          body: |
            This is an automatically created Pull Request from feature branch.

          base: main