name: Demo to create automatic PR

on:
  push:
    branches:
      - 'feature/**'

jobs:
  updateAuthor:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v2

      - name: extract git commit data
        uses: rlespinasse/git-commit-data-action@v1.x

      - name: Update author information
        run: echo ${{ env.GIT_COMMIT_AUTHOR_NAME }} > AUTHOR

      - name: Raise PR
        id: demo
        uses: peter-evans/create-pull-request@v6
        with:
          branch: ${{ github.head_ref }}  # Utilize github.head_ref para referenciar a branch da feature
          base: main
          title: "PR AUTOMATICO"
          committer: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>
          body: |
            This is to show automatic PR creation
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: false

      - name: PR url
        run: |
          echo "Pull Request URL - ${{ steps.demo.outputs.pull-request-url }}"

      - name: Show diff after PR
        run: |
          git fetch origin ${{ github.head_ref }}:${{ github.head_ref }}
          git diff main ${{ github.head_ref }}

#      - name: Approve Pull Request
#        run: |
#          pr_url=$(echo "${{ steps.demo.outputs.pull-request-url }}")
#          pr_number=$(echo "$pr_url" | cut -d'/' -f7)
#          gh pr review --approve $pr_number
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Merge Pull Request
#        uses: juliangruber/merge-pull-request-action@v1
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          number: ${{ steps.demo.outputs.pull_request_number }}
#          method: squash
#          repo: juliangruber/octokit-action