name: '1 - [feat] Build & Pull Request'

on:
  push:
    branches:
      - 'feature/**'

jobs:
  validar:
    runs-on: ubuntu-latest
    steps:
      - name: Checar o nome da branch
        run: |
          if [[ ! ${{ github.ref }} =~ ^refs/heads/feature/ ]]; then
            echo "O nome da branch não começa com 'feature/'. Use um nome de branch válido."
            exit 1
          fi
      - name: Checar repositório
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Valida sintaxe do terraform
        run: terraform validate

      - name: Solicitar Revisão de Código
        uses: actions/request-reviews@v2
        with:
          # reviewers: username1, username2
          num-reviewers: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge com a main
        if: github.event_name == 'pull_request_review' && github.event.action == 'submitted' && github.event.review.state == 'approved'
        uses: pullreminders/merge-me-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
