name: Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Run Lint
        run: |
          chmod +x ./mvnw
          ./mvnw checkstyle:check
        continue-on-error: true

      - name: Validate and Run Tests
        run: |
          chmod +x ./mvnw
          ./mvnw clean validate
          ./mvnw test
        continue-on-error: true

      - name: Build Project
        run: |
          chmod +x ./mvnw
          ./mvnw package

      - name: Build Docker Image
        run: |
          docker build -t alexcesarnascimento/dh-fiap-burger:${{ github.sha }} .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker Image to Docker Hub
        run: |
          docker push alexcesarnascimento/dh-fiap-burger:${{ github.sha }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Install kubectl
        run: |
          sudo apt-get update && sudo apt-get install -y kubectl 

      - name: Configure kubeconfig for EKS cluster
        run: |
          aws eks update-kubeconfig --name fiap-burger-eks-cluster --region us-east-1

      - name: Delete old Kubernetes resources
        run: |
          kubectl delete --all deployments --namespace=default
          kubectl delete --all pods --namespace=default
          kubectl delete --all svc --namespace=default
          kubectl delete --all configmap --namespace=default
          kubectl delete --all secret --namespace=default
          kubectl delete --all hpa --namespace=default
        continue-on-error: true

      - name: Deploy resources to EKS
        run: |
          kubectl apply -f kubernetes/constantes.configmap.yaml
          kubectl apply -f kubernetes/postgres-sql.configmap.yaml
          kubectl apply -f kubernetes/db-login.secrets.yaml
          kubectl apply -f kubernetes/fiap-burger.svc.yaml
          kubectl apply -f kubernetes/postgres.svc.yaml
          kubectl apply -f kubernetes/postgres.deployment.yaml
          kubectl apply -f kubernetes/fiap-burger.deployment.yaml
          kubectl apply -f kubernetes/fiap-burger.hpa.yaml
